---
# tasks file for sa-vpn-softether

- name: SoftEther | Check vpnserver presence
  command: test -x {{softether_home}}/vpnserver
  ignore_errors: yes
  register: vpnserver_present
  tags:
      - softether

- name: SoftEther | allow to reenter make process - reset folder
  file: path="{{softether_home}}" state="absent"
  become: yes
  when: vpnserver_present | failed
  tags:
    - softether

- name: SoftEther | Ensure target directory exists
  file: path="{{softether_home}}" state="directory"
  become: yes
  when: vpnserver_present | failed
  tags:
    - softether

- name: SoftEther | Download distribution
  get_url: url="http://www.softether-download.com/files/softether/v4.20-9608-rtm-2016.04.17-tree/Linux/SoftEther_VPN_Server/64bit_-_Intel_x64_or_AMD64/softether-vpnserver-v4.20-9608-rtm-2016.04.17-linux-x64-64bit.tar.gz" dest="/tmp/softether.tar.gz"
  become: yes
  tags:
    - softether


- name: SoftEther | unarchive
#  shell: "tar -xzf /tmp/softether.tar.gz -C {{softether_home}}"
  unarchive: src="/tmp/softether.tar.gz" dest="{{softether_location}}" remote_src=yes
  when: vpnserver_present | failed
  become: yes
  tags:
    - softether

- name: SoftEther | make
  shell: yes 1 | make
  when: vpnserver_present | failed
  args:
    chdir: "{{softether_home}}"
  tags:
    - softether


- name: SoftEther | configure lang.config
  lineinfile:  dest="{{softether_home}}/lang.config" regexp=^(en|ja|cn)$  line={{ softether_lang }}
  become: yes
  tags:
    - softether

- name: SoftEther | install init script
  template: src="{{role_dir}}/templates/startup/vpnserver.init.j2"  dest=/etc/init.d/vpnserver  mode=0755
  become: yes
  tags:
    - softether


- name: SoftEther | Enable service
  service: name="vpnserver" enabled=yes  state=started
  become: yes
  tags:
    - softether


