---
- hosts: www

  vars:
    - root_dir: ..


  pre_tasks:
    - debug: msg="Pre tasks section"

  roles:
     - {
        role: "sa-vpn-softether",
        option_install_expect_dev: true,
        option_unattended_configuration: true

       }

  tasks:

    - debug: msg="Tasks section"



